Add files via upload
Kept getting an error, and cannot commit through terminal.
 This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
error: failed to push some refs to 'https://github.com/minipompoms/Assignments.git